### PR TITLE
Lumped RLC parallel & series implementation (CSXCAD)

### PR DESCRIPTION
**Pull request by tmpusr123**
Adding a new Continuous structure parser, to support lumped RLC functionality in openEMS. As the `LumpedElement` object can only support parallel RC circuits, it is required to add an engine extension to openEMS to support more generalized lumped RLC functionality.

Although the new `LumpedRLC` CS parser is very similar to the original `LumpedElement`, it may be wise to add it separately, mainly due to the fact that the `LumpedElement` does not require building an engine extension.

The mathematical formulation is described in greater detail, in a corresponding pull request found in the openEMS repository (the two PRs are meant to be merged together).

### CODE REVIEW

**Comment by thliebig** [comment]
Can you elaborate a bit why a new class was necessary for this?
The old "LumpedElement" could have just extended e.g. to have (new) parallel and serial support and the openEMS core should not care if in some cases it needs to create an extension and in others it does not?

But in any case CSXCAD should be (and is) completely separate from openEMS and thus not even care what openEMS might or might not need...

I'm not a big fan of having a new class that is doing 95% the same as the other/old one?

**Comment by gadiLhv** [comment]
1. As stated in the original pull request, the functionality of the original lumped element is inherently different, as it does not require the creation of an engine extension.
2. Although CSXCAD and openEMS are separate, the handling of the engine extensions starts at `openems.cpp`. Specifically I tried to keep the syntax as close as possible to these lines.
```cpp
if ((m_CSX->GetQtyPropertyType(CSProperties::LORENTZMATERIAL)>0) || (m_CSX->GetQtyPropertyType(CSProperties::DEBYEMATERIAL)>0))
	FDTD_Op->AddExtension(new Operator_Ext_LorentzMaterial(FDTD_Op));
if (m_CSX->GetQtyPropertyType(CSProperties::CONDUCTINGSHEET)>0)
	FDTD_Op->AddExtension(new Operator_Ext_ConductingSheet(FDTD_Op, m_Exc->GetMaxFreq()));
```
Whereas the handling of the original `CSProperties::LUMPEDELEMENT`s only occurs in the method `Operator::Calc_LumpedElements`, called in `Operator::CalcECOperator`. It is possible to unite these classes, but that would require more extensive changes to `openEMS`, rather than `CSXCAD`.
3. This is just the beginning. Here are a couple future ideas we would like to add
3.a. First\Second order parastic models for discrete components, e.g. inductors and capacitors, to model actual SMD components.
3.b. Non-linear components (maybe LumpedRLC is a bad name for this...)

These would probably require additional parameters and enumerator entries. 

Eventually this is a matter of decision. Combining the property classes will require one of the following:

1. More extensive changes in `openems.cpp`, `operator.cpp` and maybe a couple of other places. Basically it would require checking if this is a parallel RLC with L = 0.
2. Forgoing the functionality implemented in `Operator::Calc_LumpedElements`, because the invokation of the lumpedRLC engine extension necessarily calls the pre-process and post-process methods, that are slower.

**Comment by thliebig** [comment]
Thanks for the update.
In my opinion you should go for the solution that may need more changes for openEMS instead of having multiple lumped element classes in CSXCAD, especially if you want to continue integrating new features. 
Creating redundant code to make your live easier at the beginning will always haunt you later.

And again, other tools should be able to easily use CSXCAD too and not be confused by which lumped element class is the "correct" one to use.... For example I did write a static field solver in the past that used CSXCAD and it would simulate lumped elements too and would struggle to understand what to do if the user would define a lumped element using one or the other...

Additionally I think it is no issue if openEMS would (now) always create the new extension. Either the old "Operator::Calc_LumpedElements" code would be moved to that new extension or in the case it does not need to do anything it would just not do anything. Creating an extension that does nothing is not ideal, but not really an issue either.
But moving the old code to that operator extension and then not even creating any engine extension sound good to me...

What do you think?

**Comment by gadiLhv** [comment]
Sounds more than reasonable. 

The re-write will have to happen on both **CSXCAD** and **openEMS** simultaneously, hence the pull requests will be updated when both are written and re-tested.

**Comment by gadiLhv** [comment]
Here are the main changes:

1. Both `CSPropLumpedRLC.cpp` and `CSPropLumpedRLC.h` were removed, and their entries removed from `CMakeLists.txt`.
2. The `PropertyType` enumerator at `CSProperties.h` was changed as following:
```cpp
enum PropertyType
{
	ANY = 0xffff, UNKNOWN = 0x001, MATERIAL = 0x002, METAL = 0x004, EXCITATION = 0x008, PROBEBOX = 0x010, RESBOX = 0x020, DUMPBOX = 0x040, /* unused = 0x080, */
	LUMPED_RLC = 0x500,	// Leave place here for more lumped element types
	DISPERSIVEMATERIAL = 0x100, LORENTZMATERIAL = 0x200, DEBYEMATERIAL = 0x400,
	DISCRETE_MATERIAL = 0x1000, LUMPED_ELEMENT = 0x2000, CONDUCTINGSHEET = 0x4000,
};
```
3. Only in the case that this isn't a parallel RC lumped element, the following occurs in `CSPropLumpedElement::ReadFromXML`:
```cpp
if ((m_L.GetValue() > 0.0) || (e_LEtype == LEtype::SERIES))
	Type = (CSProperties::PropertyType)(LUMPED_ELEMENT | LUMPED_RLC);
```
The last condition will have to change if more types of elements are added.

**Comment by thliebig** [comment]
I'm not sure I get this, the "PropertyType" should always only represent the available classes of properties... In this case just plain "LUMPED_ELEMENT".
If openEMS needs to determine if or maybe if not to create an engine extension, it has to ask the property for more details and cannot determine that from the type...

Additionally a type number 0x5000 is not valid, the number has to be a square number as otherwise the types can not be and/or ...

Did I misunderstand something here??

**Comment by thliebig** [comment]
Please remember, CSXCAD does not know anything about engine extensions or specific solvers or engines or anything like this... it is purely a library to describe real world objects and its material properties, nothing more.

Everything else openEMS has to figure out by determining the properties attributes, settings etc.

**Comment by gadiLhv** [comment]
I was trying to replicate the functionality demonstrated in Lorentz material. There, it is described as a Loerntz material, dispersive material, and also a just material, as such
```cpp
Type=(CSProperties::PropertyType)(LORENTZMATERIAL | DISPERSIVEMATERIAL | MATERIAL);
```
The assumption that this can be a LUMPED_ELEMENT, and also specifically a LUMPED_RLC, the same way that a material can be a dispersive material.

I can fix the indexing, easy enough. However if you would like it otherwise.

**Comment by thliebig** [comment]
Well the lorentz material class is derived from the dispersive material class which again is derived from the material class...
Thus the "Type" reflects that.
But the lumped element property class is not derived from a lumped RLC class or anthing else for that matter (except the base property which has no special type). 
Furthermore the Type is always fixed for any given class (and instance thereof) and should never depend on any internal state.

All the logic how to deal with the lumped element should be purely part of the using library/engine, if that is an FDTD (openEMS) solver or maybe a thermal solver for example should not matter.

**Comment by gadiLhv** [comment]
1. As requested, `LUMPED_RLC` type removed from enumerator
2. Condtion that added `LUMPED_RLC` removed from `CSPropLumpedElement::ReadFromXML`. Now all logic is handled in **openEMS**.
3. `GetRLCtype` and `SetRLCtype` renamed to `GetLEtype` and `SetLEtype`.

Note that in case there is no `LEtype` term in the XML file, it is set to `LEtype::PARALLEL`, to maintain regular functionality of `Calc_LumpedElements` in **openEMS**. Programs that do not use the `e_LEtype` member will be unaffected.

**Comment by thliebig** [comment]
Sounds reasonable, I think you are okay that I merge this as a squashed commit as the current history does not look too nice ;)
But this will only happens after the release of v0.0.36

**Comment by gadiLhv** [comment]
Squashing sounds good.

Thank you for the feedback!

**Comment by gadiLhv** [comment]
We had to do some modifications to enable python support.

**Comment by thliebig** [comment]
I had another quick look at this PR. It looks good in general.
Just one question, why do we need the "INVALID" as "LEtype". Would it not make more sense to have the "PARALLEL" as default and just allow to set to "SERIES" if desired?  Thus we would only need these two options?
What should a tool using this property do if the type was not set?

**Comment by gadiLhv** [comment]
I'll answer the 2nd part first. 
As I mentioned before, parallel and series are not the only options we plan to implement in the future. 
- High order parasitcs for capacitors\inductors
- Arbitrary S-parameters (reduced order models)
- Diodes or other non-linear loads.
So I'm hoping that this infrastructure is a good start.

Instinctively, adding an "invalid" option seems reasonable. In case one of these options or future ones are ill defined. Maybe I'm wrong...

**Pull request merged**
