### PR TITLE
cmake: include boost path

### PR DESCRIPTION
**Pull request by ra1nb0w**

### CODE REVIEW

**Comment by thliebig** [comment]
Sorr for the (very) late response, but why do we need this?

**Comment by ra1nb0w** [comment]
I don't remember exactly but it is required on macports (macOS package manager)

**Comment by ra1nb0w** [comment]
thank you. have a great Sunday

**Comment by ra1nb0w** [comment]
I also made https://github.com/macports/macports-ports/blob/988da34948a987d408cc5718df7357eb65d1c0e1/textproc/CSXCAD/files/clocale_fix.patch

And also for openEMS https://github.com/macports/macports-ports/blob/89a89aa86a1febcfd4ba65d00661334257a3f125/science/openEMS/files/clocale_fix.patch

**Pull request merged**
